#
# Initial script to select a topology and create the base templates for the definitions folder
#
# ansible-playbook /tf/caf/landingzones/templates/platform/asvm/walk-through.yaml \
# -e topology_folder=/tf/caf/landingzones/templates/platform/asvm/orion \
# -e config_folder_platform_templates=/tf/caf/landingzones/templates/platform \
# -e landingzones_folder=/tf/caf/landingzones \
# -e destination_folder=/tf/caf/definitions/asvm/orion

- name: Deploy template to definition's folder
  hosts: localhost

  tasks:

    - name: Get template files
      register: asvm_files
      find:
        paths: {{topology_file}}
        file_type: file

    - debug:
        - msg: "{{asvm_files}}" 

    - name: Deploy files
      ansible.builtin.template:
        src: "{{topology_folder}}/{{item}}"
        dest: "{{destination_folder}}/{{item}}"
        loop: 