- name: Process deployment based on bootstrap.yaml
  hosts: localhost

  tasks:
        
    - name: "load {{ config_folder }}/bootstrap.yaml"
      include_vars:
        name: bootstrap
        dir: "{{ config_folder }}"
        depth: 1
        ignore_unknown_extensions: true
        files_matching: "bootstrap.yaml"

    - name: "Load variable for landingzones config"
      include_vars:
        name: asvm_config__to_merge
        dir: "{{config_folder}}"
        depth: 1
        ignore_unknown_extensions: true
        files_matching: "config.asvm.yaml|tfstates.asvm.yaml|deployments.yaml"

    - name: "Load variable for platform config"
      include_vars:
        name: platform_config__to_merge
        dir: "{{config_folder_platform | default(config_folder)}}"
        depth: 1
        ignore_unknown_extensions: true
        files_matching: "caf.platform.yaml|tfstates.caf.yaml|tfstates.yaml|subscriptions.yaml"

    - name: Merge asvm and platform variables
      merge_vars:
        suffix_to_merge: config__to_merge
        merged_var_name: config
        expected_type: 'dict'
        recursive_dict_merge: True

    - name: "Get latest cache folder"
      set_fact:
        job_cache_base_path: "/home/vscode/.terraform.cache"
        destination_base: '{{config.configuration_folders.platform.destination_base_path}}'
        config: "{{ ansible_facts.config }}"

    - debug:
        msg: 
        - "{{bootstrap}}"
        - "{{config}}"
        # verbosity: 2

#
# Generate the foundation services
#

    - include_tasks: "process_foundations.yaml"
      loop: "{{bootstrap.deployments.keys()}}"
      when: bootstrap != {}
      loop_control:
        loop_var: stage
      vars:
        step: deployments

#
# Process the deployments folders
#

    - find:
        paths: "{{config_folder}}/deployments"
        recurse: yes
        patterns: "*.yaml"
        file_type: file
      register: files_to_process

    - debug:
        msg:
        - "{{files_to_process}}"
        verbosity: 2


    - name: Process deployments folder configuration files
      include_tasks: "process_deployments.yaml"
      loop: "{{files_to_process.files}}"
      loop_control:
        loop_var: file_to_process

## Platform readme

    - name: "[{{ base_templates_folder }}] readme"
      ansible.builtin.template:
        src: "{{ base_templates_folder }}/readme.md"
        dest: "{{ destination_base }}/{{ config.configuration_folders.platform.destination_relative_path }}/readme.md"
        force: yes

#
# Formatting & Linters
#

    - name: Terraform Formatting
      shell: |
        terraform fmt -recursive {{ destination_base }}/{{ config.configuration_folders.platform.destination_relative_path }}

