- name: Process deployment based on bootstrap.yaml
  hosts: localhost

  tasks:
        
    - name: "load {{ config_folder }}/bootstrap.yaml"
      include_vars:
        name: bootstrap
        dir: "{{ config_folder }}"
        depth: 1
        ignore_unknown_extensions: true
        files_matching: "bootstrap.yaml"

    - name: "Load variable for platform config"
      include_vars:
        name: config
        dir: "{{config_folder}}"
        depth: 1
        ignore_unknown_extensions: true
        files_matching: "caf.platform.yaml|tfstates.caf.yaml|tfstates.yaml|subscriptions.yaml"


    - name: "{{deployment}} - Set tfstate_object"
      set_fact:
        destination_base: '{{config.configuration_folders.platform.destination_base_path}}'

    - debug:
        msg: 
        - "{{bootstrap}}"
        - "{{config}}"
        verbosity: 2

#
# Generate the foundation services
#

    - include_tasks: "process_foundations.yaml"
      loop: "{{bootstrap.deployments.keys()}}"
      when: bootstrap is defined
      loop_control:
        loop_var: stage
      vars:
        step: deployments

#
# Process the deployments folders
#

    - find:
        paths: "{{config_folder}}/deployments"
        recurse: yes
        patterns: "*.yaml"
        file_type: file
      register: files_to_process

    - debug:
        msg:
        - "{{files_to_process}}"
        verbosity: 2


    - name: Process deployments folder configuration files
      include_tasks: "process_deployments.yaml"
      loop: "{{files_to_process.files}}"
      loop_control:
        loop_var: file_to_process

## Platform readme

    - name: "[{{ base_templates_folder }}] readme"
      ansible.builtin.template:
        src: "{{ base_templates_folder }}/readme.md"
        dest: "{{ destination_base }}/{{ config.configuration_folders.platform.destination_relative_path }}/readme.md"
        force: yes

#
# Formatting & Linters
#

    - name: Terraform Formatting
      shell: |
        terraform fmt -recursive {{ destination_base }}/{{ config.configuration_folders.platform.destination_relative_path }}

