- debug:
    msg:
      - "{{lz_type}}"
      - "{{deployment}}"
      - "{{env}}"

- name: "Verify {{deployment}} {{lz_type}} is defined under tfstates:platform in {{config_folder}}/tfstates.yaml :"
  debug:
    msg: 
    - "{{resources.tfstates[lz_type]['eslz_' + tfstate] if stage == 'eslz' else resources.tfstates[lz_type][deployment] if env == '' else resources.tfstates[lz_type][deployment][env]}}"

- name: "{{deployment}} - tfstate_object sub_template_folder- {{env}}"
  debug:
    msg: 
    - 'sub_template_folder - {{tfstate_object.sub_template_folder | default()}}'
    - 'tfstate_object      - {{tfstate_object}}'

- name: "{{deployment}} - process subscription resources"
  include_tasks: "process_subscription_resources.yaml"
  loop: "{{resources['eslz_' + tfstate].subscriptions.keys() if stage == 'eslz' else resources[tfstate].subscriptions.keys() if env == '' else resources[tfstate + '_' + env].subscriptions.keys() }}"
  loop_control:
    loop_var: subscription_key
  vars:
    level: "{{tfstate_object.level}}"
